In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.2.6


In [2]:

a = np.array([1, 2, 3, 4, 5])
print('1D Array:', a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print('2D Array:\n', b)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('3D Array:\n', c)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:

print('zeros:\n', np.zeros((3, 3)))
print('ones:\n', np.ones((2, 4)))
print('full (7):\n', np.full((2, 3), 7))
print('identity:\n', np.eye(4))
print('empty:\n', np.empty((2, 2)))
print('arange:', np.arange(0, 20, 2))
print('linspace:', np.linspace(0, 1, 6))
print('random:', np.random.rand(3, 3))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full (7):
 [[7 7 7]
 [7 7 7]]
identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
empty:
 [[1. 1.]
 [1. 1.]]
arange: [ 0  2  4  6  8 10 12 14 16 18]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]
random: [[0.73266763 0.75963891 0.86311493]
 [0.14813069 0.34373485 0.99689302]
 [0.74600033 0.37820314 0.25170931]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)
print('Dimensions (ndim):', arr.ndim)
print('Size (total elements):', arr.size)
print('Data type:', arr.dtype)
print('Item size (bytes):', arr.itemsize)
print('Total bytes:', arr.nbytes)

Shape: (2, 3)
Dimensions (ndim): 2
Size (total elements): 6
Data type: int64
Item size (bytes): 8
Total bytes: 48


In [5]:
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1.1, 2.2, 3.3], dtype=np.float64)
c = np.array([True, False, True], dtype=np.bool_)
d = np.array(['hello', 'world'], dtype=np.str_)
print(a.dtype, b.dtype, c.dtype, d.dtype)

e = a.astype(np.float64)
print('Casted to float:', e)

int32 float64 bool <U5
Casted to float: [1. 2. 3.]


In [6]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print('Full array:\n', arr)
print('Element [0][2]:', arr[0][2])
print('Element [1,3]:', arr[1,3])
print('First row:', arr[0])
print('Last row:', arr[-1])
print('First column:', arr[:, 0])
print('Slice rows 0-1, cols 1-3:\n', arr[0:2, 1:3])
print('Every other col:', arr[:, ::2])

Full array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Element [0][2]: 30
Element [1,3]: 80
First row: [10 20 30 40]
Last row: [ 90 100 110 120]
First column: [10 50 90]
Slice rows 0-1, cols 1-3:
 [[20 30]
 [60 70]]
Every other col: [[ 10  30]
 [ 50  70]
 [ 90 110]]


In [7]:
arr = np.arange(1, 13)
print('Original:', arr)
print('Reshape to (3,4):\n', arr.reshape(3, 4))
print('Reshape to (2,6):\n', arr.reshape(2, 6))
print('Reshape to (2,2,3):\n', arr.reshape(2, 2, 3))

arr2d = arr.reshape(3, 4)
print('Flatten:', arr2d.flatten())
print('Ravel:', arr2d.ravel())
print('Transpose:\n', arr2d.T)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape to (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape to (2,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshape to (2,2,3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print('Add:', a + b)
print('Subtract:', a - b)
print('Multiply:', a * b)
print('Divide:', a / b)
print('Floor Divide:', a // b)
print('Modulus:', a % b)
print('Power:', a ** 2)
print('Scalar add:', a + 5)
print('Scalar multiply:', a * 3)

Add: [11 22 33 44]
Subtract: [ 9 18 27 36]
Multiply: [ 10  40  90 160]
Divide: [10. 10. 10. 10.]
Floor Divide: [10 10 10 10]
Modulus: [0 0 0 0]
Power: [ 100  400  900 1600]
Scalar add: [15 25 35 45]
Scalar multiply: [ 30  60  90 120]


In [9]:
arr = np.array([1, 4, 9, 16, 25])
print('sqrt:', np.sqrt(arr))
print('square:', np.square(arr))
print('abs:', np.abs(np.array([-1, -2, 3])))
print('exp:', np.exp(np.array([1, 2, 3])))
print('log:', np.log(arr))
print('log2:', np.log2(arr))
print('log10:', np.log10(arr))
print('sin:', np.sin(np.pi/2))
print('cos:', np.cos(0))
print('floor:', np.floor([1.7, 2.3]))
print('ceil:', np.ceil([1.2, 2.8]))
print('round:', np.round([1.567, 2.345], 2))

sqrt: [1. 2. 3. 4. 5.]
square: [  1  16  81 256 625]
abs: [1 2 3]
exp: [ 2.71828183  7.3890561  20.08553692]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
log2: [0.         2.         3.169925   4.         4.64385619]
log10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]
sin: 1.0
cos: 1.0
floor: [1. 2.]
ceil: [2. 3.]
round: [1.57 2.35]


In [10]:
arr = np.array([[4, 7, 2], [3, 9, 1], [6, 5, 8]])
print('Array:\n', arr)
print('min:', np.min(arr))
print('max:', np.max(arr))
print('sum:', np.sum(arr))
print('mean:', np.mean(arr))
print('median:', np.median(arr))
print('std (standard deviation):', np.std(arr))
print('var (variance):', np.var(arr))
print('sum along rows (axis=1):', np.sum(arr, axis=1))
print('sum along cols (axis=0):', np.sum(arr, axis=0))
print('min index (argmin):', np.argmin(arr))
print('max index (argmax):', np.argmax(arr))
print('cumulative sum:', np.cumsum(arr))
print('percentile 75:', np.percentile(arr, 75))

Array:
 [[4 7 2]
 [3 9 1]
 [6 5 8]]
min: 1
max: 9
sum: 45
mean: 5.0
median: 5.0
std (standard deviation): 2.581988897471611
var (variance): 6.666666666666667
sum along rows (axis=1): [13 13 19]
sum along cols (axis=0): [13 21 11]
min index (argmin): 5
max index (argmax): 4
cumulative sum: [ 4 11 13 16 25 26 32 37 45]
percentile 75: 7.0


In [11]:
arr = np.array([5, 15, 25, 35, 45, 55])

print('Values > 20:', arr[arr > 20])
print('Values between 10 and 40:', arr[(arr > 10) & (arr < 40)])

print('np.where > 20:', np.where(arr > 20, arr, 0))
print('Select index 0,2,4:', arr[[0, 2, 4]])
print('Any > 50:', np.any(arr > 50))
print('All > 0:', np.all(arr > 0))

Values > 20: [25 35 45 55]
Values between 10 and 40: [15 25 35]
np.where > 20: [ 0  0 25 35 45 55]
Select index 0,2,4: [ 5 25 45]
Any > 50: True
All > 0: True


In [12]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print('Original:', arr)
print('Sorted:', np.sort(arr))
print('Argsort (sorted indices):', np.argsort(arr))
print('Unique values:', np.unique(arr))
print('Unique with counts:', np.unique(arr, return_counts=True))
arr2d = np.array([[3,1,2],[9,5,6]])
print('Sort along axis=1:\n', np.sort(arr2d, axis=1))

Original: [3 1 4 1 5 9 2 6]
Sorted: [1 1 2 3 4 5 6 9]
Argsort (sorted indices): [1 3 6 0 2 4 7 5]
Unique values: [1 2 3 4 5 6 9]
Unique with counts: (array([1, 2, 3, 4, 5, 6, 9]), array([2, 1, 1, 1, 1, 1, 1]))
Sort along axis=1:
 [[1 2 3]
 [5 6 9]]


In [13]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('vstack (vertical):\n', np.vstack((a, b)))
print('hstack (horizontal):\n', np.hstack((a, b)))
print('concatenate axis=0:\n', np.concatenate((a, b), axis=0))
print('concatenate axis=1:\n', np.concatenate((a, b), axis=1))

arr = np.arange(1, 13).reshape(3, 4)
print('hsplit into 2:\n', np.hsplit(arr, 2))
print('vsplit into 3:\n', np.vsplit(arr, 3))

vstack (vertical):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack (horizontal):
 [[1 2 5 6]
 [3 4 7 8]]
concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]
hsplit into 2:
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
vsplit into 3:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [14]:

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30]) 
print('Array a + row b (broadcasting):\n', a + b)

c = np.array([[100], [200]])  
print('Array a + col c (broadcasting):\n', a + c)

Array a + row b (broadcasting):
 [[11 22 33]
 [14 25 36]]
Array a + col c (broadcasting):
 [[101 102 103]
 [204 205 206]]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('Matrix multiply (dot):\n', np.dot(A, B))
print('Matrix multiply (@):\n', A @ B)
print('Determinant:', np.linalg.det(A))
print('Inverse:\n', np.linalg.inv(A))
print('Eigenvalues:', np.linalg.eigvals(A))
vals, vecs = np.linalg.eig(A)
print('Eigenvectors:\n', vecs)
print('Transpose:\n', A.T)
print('Trace (sum of diagonal):', np.trace(A))

Matrix multiply (dot):
 [[19 22]
 [43 50]]
Matrix multiply (@):
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Transpose:
 [[1 3]
 [2 4]]
Trace (sum of diagonal): 5


In [16]:
np.random.seed(42)  
print('rand (uniform 0-1):', np.random.rand(3, 3))
print('randn (normal dist):', np.random.randn(3, 3))
print('randint (0-10):', np.random.randint(0, 10, size=(3, 3)))
print('choice:', np.random.choice([10, 20, 30, 40, 50], size=3))
arr = np.arange(10)
np.random.shuffle(arr)
print('shuffled:', arr)
print('normal dist:', np.random.normal(loc=0, scale=1, size=5))
print('uniform dist:', np.random.uniform(1, 10, size=5))

rand (uniform 0-1): [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
randn (normal dist): [[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]
randint (0-10): [[2 6 3]
 [8 2 4]
 [2 6 4]]
choice: [10 20 40]
shuffled: [6 3 2 5 4 7 0 9 1 8]
normal dist: [-0.74240684 -0.01349722 -1.05771093  0.82254491 -1.22084365]
uniform dist: [3.80539968 5.68061219 5.92039251 2.6636901  9.72626165]


In [17]:
original = np.array([1, 2, 3, 4, 5])

view = original[1:4]
view[0] = 99
print('After modifying view, original:', original)

original2 = np.array([1, 2, 3, 4, 5])
copy = original2.copy()
copy[0] = 99
print('After modifying copy, original2:', original2)

After modifying view, original: [ 1 99  3  4  5]
After modifying copy, original2: [1 2 3 4 5]


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save and load as .npy
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print('Loaded from .npy:\n', loaded)

# Save multiple arrays
np.savez('arrays.npz', a=arr, b=arr*2)
data = np.load('arrays.npz')
print('Loaded a:', data['a'])
print('Loaded b:', data['b'])

# Save as CSV
np.savetxt('array.csv', arr, delimiter=',')
loaded_csv = np.loadtxt('array.csv', delimiter=',')
print('Loaded from CSV:\n', loaded_csv)

Loaded from .npy:
 [[1 2 3]
 [4 5 6]]
Loaded a: [[1 2 3]
 [4 5 6]]
Loaded b: [[ 2  4  6]
 [ 8 10 12]]
Loaded from CSV:
 [[1. 2. 3.]
 [4. 5. 6.]]
